#!/usr/bin/env bash

# https://www.reddit.com/r/neovim/comments/aex45u/integrating_nvr_and_tmux_to_use_a_single_tmux_per/
if [[ -n "$@" ]]; then
  /usr/bin/nvr -s "$@"
else
  /usr/bin/nvr -s newfile
fi
if [[ -v TMUX ]]; then
  tmux select-pane -t 0
fi
