#!/bin/sh

# https://unix.stackexchange.com/questions/157328/how-can-i-remove-all-comments-from-a-file
# https://stackoverflow.com/questions/16414410/delete-empty-lines-using-sed
# https://stackoverflow.com/questions/4824590/propagate-all-arguments-in-a-bash-shell-script

sed '/^[[:blank:]]*#/d;s/#.*//;/^\s*$/d' "$@"
