#!/usr/bin/env bash

MY_USER='dima-test'
MY_GROUP='dima-test'
MY_DIRECTORY=$(eval echo ~$MY_USER)

MY_UID=$(id -u $MY_USER)

if [ ! -d "$MY_DIRECTORY" ]; then
  echo "Directory $MY_DIRECTORY does not exists."
  exit 1
fi

read -p "Are you sure ($MY_DIRECTORY)? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

pkill -u $MY_USER &&

echo "rm -r /var/run/user/$MY_UID/"
rm -r /var/run/user/$MY_UID/

# TODO spaces in dirname
echo "rm -r $MY_DIRECTORY/"
rm -r $MY_DIRECTORY/ &&

cp -rv /etc/skel.dima/ $MY_DIRECTORY/ &&
# cp -rv /etc/skel/ $MY_DIRECTORY/ &&

ln -sf /usr/share/sddm/faces/$MY_USER.face.icon $MY_DIRECTORY/.face &&
ln -sf $MY_DIRECTORY/.face $MY_DIRECTORY/.face.icon &&
chmod 700 $MY_DIRECTORY/ &&
chown -R $MY_USER:$MY_GROUP $MY_DIRECTORY/
